//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerNewUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrackerNewUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Administration ähnelt.
        /// </summary>
        public static string ADMIN_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("ADMIN_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active ähnelt.
        /// </summary>
        public static string ADMIN_CAT_TABLE_ACTIVE {
            get {
                return ResourceManager.GetString("ADMIN_CAT_TABLE_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category Name ähnelt.
        /// </summary>
        public static string ADMIN_CAT_TABLE_CATEGORY {
            get {
                return ResourceManager.GetString("ADMIN_CAT_TABLE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string ADMIN_DELETE_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("ADMIN_DELETE_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        public static string ADMIN_NEW_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("ADMIN_NEW_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category ähnelt.
        /// </summary>
        public static string CATEGORY_LABEL_TEXT {
            get {
                return ResourceManager.GetString("CATEGORY_LABEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you delete &quot;{CATEGORY_NAME}&quot;, all tracked times for this category will get lost. Continue? ähnelt.
        /// </summary>
        public static string CONFIRM_CATEGORY_DELETE {
            get {
                return ResourceManager.GetString("CONFIRM_CATEGORY_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm ähnelt.
        /// </summary>
        public static string CONFIRM_HEADER {
            get {
                return ResourceManager.GetString("CONFIRM_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are not allowed to delete active categories. ähnelt.
        /// </summary>
        public static string ERROR_CATEGORY_IS_ACTIVE {
            get {
                return ResourceManager.GetString("ERROR_CATEGORY_IS_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string ERROR_HEADER {
            get {
                return ResourceManager.GetString("ERROR_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No category chosen. ähnelt.
        /// </summary>
        public static string ERROR_NO_CATEGORY_CHOSEN {
            get {
                return ResourceManager.GetString("ERROR_NO_CATEGORY_CHOSEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        public static string EXIT_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("EXIT_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Tracker ähnelt.
        /// </summary>
        public static string MAIN_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("MAIN_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string NO_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("NO_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string OK_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("OK_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Processing ähnelt.
        /// </summary>
        public static string PROCESSING_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("PROCESSING_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reporting ähnelt.
        /// </summary>
        public static string REPORTING_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("REPORTING_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        public static string START_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("START_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop ähnelt.
        /// </summary>
        public static string STOP_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("STOP_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string YES_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("YES_BUTTON_TEXT", resourceCulture);
            }
        }
    }
}
